#!/bin/bash

##
# Setting script version
#
installdrupal_version=7

##
# Script source
#
installdrupal_fonts_uri=https://raw.githubusercontent.com/danilocgsilva/download_drupal/master/src/downloaddrupal

##
# Called whenever the dependencies are not met and if the script is unable do download them
#
installdrupal_dependencies() {
	echo This script needs:
	echo downloaddrupal. Get from: https://raw.githubusercontent.com/danilocgsilva/download_drupal/master/programfiles/downloaddrupal
    echo addvhost. Get from https://raw.githubusercontent.com/danilocgsilva/addvhost3/master/programfiles/addvhost
	echo ask_shell. Get from https://raw.githubusercontent.com/danilocgsilva/ask_shell/master/programfiles/askshell
}

##
# Check if ask_mysql exists in the system, so the local database can be created.
#
ask_mysql_can_execute=0
# First, verify if mysql client is installed in the system
if which mysql > /dev/null 2>&1; then
	# Second, verify if ask_mysql utility is installed in the system
	if [ $(which ask_mysql 2> /dev/null) ]; then
		ask_mysql_can_execute=1
	fi
fi

##
# Check for downloaddrupal dependency. Tries to download or warns about the dependency missing.
#
if ! downloaddrupal_source=$(which downloaddrupal 2> /dev/null); then
	if which installfromuri > /dev/null 2>&1; then
		installfromuri $installdrupal_fonts_uri
	else
		echo Did not have installed the downloaddrupal utility.
		installdrupal_dependencies
		exit
	fi
fi

if ! askshell_source=$(which askshell 2> /dev/null); then
	if which askshell > /dev/null 2>&1; then
		installfromuri https://raw.githubusercontent.com/danilocgsilva/ask_shell/master/programfiles/askshell
	else
		echo Did not have installed the askshell utility.
		installdrupal_dependencies
		exit
	fi
fi

##
# Checking if the first argument, which is required, was provided
#
if [ -z $1 ]; then
	echo You must provides the first argument to be the hostname.
	exit
fi

# Check for addvhost dependency. Tries to download or warns about the dependency missing.
if ! addvhost_source=$(which addvhost 2> /dev/null); then
	if which installfromuri > /dev/null 2>&1; then
		installfromuri https://raw.githubusercontent.com/danilocgsilva/addvhost/master/programfiles/addvhost
	else
		echo did not have installed the addvhost utility.
		installdrupal_dependencies
		exit
	fi
fi


## End of checkings. Script execution

# Asks for database information to create one. Skip if the ask_mysql utility is not in the system.
if [ $ask_mysql_can_execute -eq 1 ]; then
	echo Provides the database information to create one.
	source ask_mysql
	mysqladmin -u$mysql_user -p$mysql_databasepassword -h$mysql_host create $mysql_databasename
	echo Database $mysql_databasename created.
else
	echo Could not ask for mysql database credentials to create it. Download and install the ask_mysql from https://raw.githubusercontent.com/danilocgsilva/ask_mysql/master/programfiles/ask_mysql, so next time it is possible to create the database automatically.
fi

source $addvhost_source
source $downloaddrupal_source
downloaddrupal_download $1 $2

mv $1 $htdocs_root


echo Don\'t forget to restart the web server.
