#!/bin/bash

# Setting script version
installdrupal_version=4
# Script source
installdrupal_fonts_uri=https://raw.githubusercontent.com/danilocgsilva/download_drupal/master/programfiles/downloaddrupal

# Checking if the first argument, which is required, was provided
if [ -z $1 ]; then
	echo You must provides the first argument to be the hostname.
	exit
fi

installdrupal_dependencies() {
	echo This script needs:
	echo downloaddrupal. Get from: https://raw.githubusercontent.com/danilocgsilva/download_drupal/master/programfiles/downloaddrupal
    echo addvhost. Get from https://raw.githubusercontent.com/danilocgsilva/addvhost3/master/programfiles/addvhost
}

downloaddrupal_source=$(which downloaddrupal 2> /dev/null)
if [ $? != 0 ]; then
	echo did not have installed the downloaddrupal utility.
	installdrupal_dependencies
	exit
fi

addvhost_source=$(which addvhost)
if [ $? != 0 ]; then
	echo did not have installed the addvhost utility.
	installdrupal_dependencies
	exit
fi

source $addvhost_source
source $downloaddrupal_source
downloaddrupal_download $1 $2

mv $1 $htdocs_root

echo Don\'t forget to restart the web server.
